language: android
dist: trusty
os: linux

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
  - cp local.properties.ci local.properties

android:
  components:
    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew build detekt connectedCheck